### ISSUE TITLE
Ошибка при чтении карты

### ISSUE THREAD

**Issue by Dereku** [semyon422/lua-mania#1]
Карта: http://puu.sh/shYt0/13dc5940d5.osz
Сборка: #166, #167

Error: Could not open WAVE
stack traceback:
        [C]: at 0x7ffe713f9ef0
        [C]: in function 'newSource'
        ./src/luaMania/game/modes/vsrg/Column.lua:21: in function 'load'
        ./src/loveio\LoveioObject.lua:16: in function 'update'
        ./src/luaMania/game//modes/vsrg/init.lua:144: in function 'load'
        ./src/loveio\LoveioObject.lua:16: in function 'update'
        ./src/loveio/init.lua:14: in function 'update'
        ./src/loveio/init.lua:50: in function <./src/loveio/init.lua:22>
        [C]: in function 'xpcall'

**Comment by semyon422** [comment]
Вобщем love2d наотрез отказывается брать формат из файла и берёт его из расширения. Сделал обход таких ситуаций использованием пустого хитсаунда и добавил предупреждение в консоль.
